title: "Adrian Iacovlev"
description: "Notes on software, work, and AI."
url: "https://adiacov.github.io"
baseurl: ""

permalink: /:year/:month/:day/:title/

markdown: kramdown

exclude:
  - README.md
